export const GAME_CONSTANTS = {
  MIN_PLAYERS: 2,
  MAX_PLAYERS: 12,
  DEFAULT_ROUND_TIME_SECONDS: 80,
  MIN_ROUND_TIME_SECONDS: 30,
  MAX_ROUND_TIME_SECONDS: 180,
  MAX_ROUNDS: 10,
  MAX_CHAT_MESSAGE_LENGTH: 200,
  MAX_PLAYER_NAME_LENGTH: 20,
  MIN_PLAYER_NAME_LENGTH: 2,
  ROOM_CODE_LENGTH: 6,
} as const;